export const conditions = [
  "Has fur",
  "Has feathers",
  "Lays eggs",
  "Is a mammal",
  "Can fly",
  "Lives in water",
  "Has scales",
  "Is a carnivore",
  "Is a herbivore",
  "Has a tail",
  "Is nocturnal",
  "Can swim",
  "Has hooves",
  "Is domesticated",
  "Has sharp claws",
  "Has long ears",
  "Is larger than a dog",
  "Is smaller than a cat",
  "Can climb trees",
  "Is cold-blooded",
  "Has a long neck",
  "Has a shell",
  "Has webbed feet",
  "Is a predator",
  "Has a long tongue",
  "Is social",
  "Has a beak",
  "Can camouflage",
  "Lives in the jungle",
  "Lives in the desert"
]